# Generated by Django 5.0.6 on 2024-06-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='zapatos/'),
        ),
        migrations.AddField(
            model_name='zapato',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
