# Generated by Django 5.0.6 on 2024-06-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_zapato_imagen_zapato_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
