# Generated by Django 5.0.6 on 2024-06-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_zapato_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapato',
            name='marca',
            field=models.IntegerField(choices=[(1, 'Adidas'), (2, 'Converse'), (3, 'Nike')], default=1),
        ),
        migrations.AlterField(
            model_name='zapato',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
